/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Prize;

/**
 *
 * @author bechma
 */
public class PrizeView extends javax.swing.JPanel {
    protected Prize prizeModel;
    
    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        niveles = new javax.swing.JLabel();
        tesoros = new javax.swing.JLabel();
        etiqNiveles = new javax.swing.JLabel();
        etiqTesoros = new javax.swing.JLabel();

        niveles.setText("Levels");

        tesoros.setText("Treasures");

        etiqNiveles.setText("Niveles: ");

        etiqTesoros.setText("Tesoros: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqNiveles)
                        .addGap(18, 18, 18)
                        .addComponent(niveles))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqTesoros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tesoros)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqNiveles)
                    .addComponent(niveles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tesoros)
                    .addComponent(etiqTesoros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setPrize(Prize p){
        prizeModel = p;
        
        this.niveles.setText(prizeModel.getLevel() + "");
        this.tesoros.setText(prizeModel.getTreasures() + "");
        
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqNiveles;
    private javax.swing.JLabel etiqTesoros;
    private javax.swing.JLabel niveles;
    private javax.swing.JLabel tesoros;
    // End of variables declaration//GEN-END:variables
}
